### ISSUE TITLE
Display issues for Fishing

### ISSUE THREAD

**Issue by kriana** [Jelidity/DBM-CC-Patches#12]
> Okay, just realized I forgot to test replicas. All 5 replacer rings don't accept their replica, though with the ToK patch the Ring of the Wind replica displays, but also rotates it replica or no (will add picture), every ring is correctly rotated otherwise (And Wind is properly rotated without ToK patch). Fang works replica or no.
> Neither the CRF or ToK versions display, as intended presumably.
> Heavy Armory versions of the Fishing Nord weapons are not accepted.
> Every other replica I could find works, the 5 replaced rings do not

Reporter: Be
![ScreenShot56](https://user-images.githubusercontent.com/7259933/153289711-d670b8ad-f201-40ac-9d4f-579ac911dc1f.png)
n

**Comment by Jelidity** [comment]
position fixed

**Comment by Jelidity** [comment]
Nothing else here is an issue
