### ISSUE TITLE
Staves Activators/displays seem to be swapped

### ISSUE THREAD

**Issue by kriana** [Jelidity/DBM-CC-Patches#26]
> the activator for the light wood stave expects and looks for a dark wood stave, with the inverse happening for the activator for the dark wood stave. 

> It does, however, "correctly" update the dark wood stave display when you use the display chest and the display table with only a dark wood stave, inverse being true for the light wood stave. 
this makes the dark wood stave unremovable if you added it via the table/chest unless you also add the light wood stave to the display using the table/chest, and the inverse is true with the light wood stave. 

> this also makes it possible to "fill" both displays with only one type of wooden stave, putting it in the chest/using the table to display the first stave, and then activating the other stave's display.

Reporter: Freedan

**Comment by Jelidity** [comment]
Fixed
