### ISSUE TITLE
If you take Bloodthirst off display, the activator disables. Additionally displaying the replica yields the orig when taken off display

### ISSUE THREAD

**Issue by kriana** [Jelidity/DBM-CC-Patches#4]
> More seriously, when I place Bloodthirst on its display in the HoW, it displays fine, but any attempt to remove it results in the activator disabling itself, and I'm unable to attempt to place it again without reloading a previous save.  What's more, placing the replica in that spot returns a copy of the original artifact. If I then go back up to the Keeper of Secrets and access the Museum safe, the replica is still stuck in there, but removing it doesn't re-enable the activator

Reported by Nova

**Comment by Jelidity** [comment]
Fixed
